site_name: Cours de programmation orientée objet 2
site_url: https://profdenis.github.io/3n1_doc
repo_name: profdenis/3n1_doc
repo_url: https://github.com/profdenis/3n1_doc
nav:
  - Accueil: index.md
  - Intro:
      - introduction/01_index.md
      - introduction/02_transition.md
      - introduction/03_uv.md
  - 1. Python (bases):
      - section1/01_survol_python.md
      - section1/02_exercices1.md
      - section1/03_exercices2.md
      - section1/04_comprehensions.md
      - section1/05_exercices3.md
      - section1/06_chaines.md
      - section1/07_exercices4.md
      - section1/08_fonctions.md
      - section1/09_exercices5.md
      - Fichiers:
        - section1/fichiers/01_intro.md
        - section1/fichiers/02-special-cases.md
        - section1/fichiers/03-csv.md
        - section1/fichiers/04-json.md
        - section1/fichiers/05-toml.md
        - section1/fichiers/06-yaml.md
  - 2. Python (bases OO):
      - section2/01_bases.md
      - section2/02_heritage.md
      - section2/03_match.md
      - section2/04_polymorphisme.md
      - section2/05_exercices.md
  - 3. Qt et PySide6:
      - A. Introduction:
        - section3/A_intro/01_hello_world.md
        - section3/A_intro//02_signal_slot.md
        - section3/A_intro//03_agencements.md
        - section3/A_intro//04_widgets.md
        - section3/A_intro//05_exemples_box_layouts.md
        - section3/A_intro//06_exemples_grid_layout.md
        - section3/A_intro//07_exemple_formulaire.md
      - B. Signaux et Slots:
        - section3/B_signaux/01_bouton.md
        - section3/B_signaux/02_synchro.md
        - section3/B_signaux/03_signal_perso.md
        - section3/B_signaux/04_form.md
      - C. Menus et Dialogues:
        - section3/C_menus/01_intro.md
        - section3/C_menus/02_editeur1.md
        - section3/C_menus/03_editeur2.md
        - section3/C_menus/04_editeur3.md
        - section3/C_menus/05_editeur4.md
        - section3/C_menus/06_editeur5.md
      - D. Événements:
        - section3/D_evenements/01_intro.md
        - section3/D_evenements/02_propagation.md
      - E. Exercices:
          - section3/E_exercices/01_compteur.md
      - F. QThread:
          - section3/F_QThread/01_intro.md
          - section3/F_QThread/02_avance.md
          - section3/F_QThread/03_tableau.md
          - section3/F_QThread/04_arret.md
          - section3/F_QThread/05_arret_progressif.md
  - 4. Encapsulation et intégrité:
      - section4/01_static.md
      - section4/02_proprietes.md
      - section4/03_types.md
      - section4/04_exceptions.md
      - section4/05_dbc.md
      - section4/06_pytest.md
      - section4/07_dbc_pytest.md
      - section4/08_encapsulation.md
  - 5. Python (OO avancé):
      - section5/01_abc.md
      - section5/01a_dict.md
      - section5/02_generiques.md
      - section5/03_protocoles.md
      - section5/04_heritage_multiple.md
  - 6. Patrons de conception:
      - section6/01_principes_OO.md
      - section6/02_Patrons_de_conception.md
      - section6/03_creation1_fabrique.md
      - section6/04_creation2.md
      - section6/05_structuraux.md
      - section6/06_comportementaux.md
  - 7. Pygame:
      - section7/01_bases.md

theme:
  name: material
  locale: fr
  language: fr
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    logo: material/language-python
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


extra_css:
  - style.css

markdown_extensions:
  smarty: { }
  toc:
    permalink: true
  sane_lists: { }
  admonition: { }
  attr_list: { }
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.inlinehilite: { }
  pymdownx.snippets: { }
  pymdownx.superfences: { }
  pymdownx.fancylists: { }
  pymdownx.saneheaders: { }
  pymdownx.mark: { }
  pymdownx.tabbed: { }
  pymdownx.tasklist: { }
  pymdownx.tilde: { }
  pymdownx.details: { }
  pymdownx.arithmatex:
    generic: true

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        enabled: false
  - search: { }