site_name: Cours de programmation orientée objet 2
site_url: https://profdenis.github.io/3n1_doc
repo_name: profdenis/3n1_doc
repo_url: https://github.com/profdenis/3n1_doc
nav:
  - Accueil: index.md
  - Intro:
    - introduction/01_index.md
    - introduction/02_transition.md
  - 1. Python (bases):
    - section1/01_survol_python.md
    - section1/02_exercices1.md
    - section1/03_exercices2.md
    - section1/04_comprehensions.md
    - section1/05_exercices3.md
    - section1/06_chaines.md
    - section1/07_exercices4.md
    - section1/08_fonctions.md
    - section1/09_exercices5.md
  - 2. Python (bases OO):
    - section2/01_bases.md
    - section2/02_heritage.md
    - section2/03_match.md
    - section2/04_polymorphisme.md
    - section2/05_exercices.md
  - 3. Encapsulation et intégrité :
    - section3/01_static.md
    - section3/02_proprietes.md
    - section3/03_types.md
    - section3/04_exceptions.md
    - section3/05_dbc.md
    - section3/06_pytest.md
    - section3/07_dbc_pytest.md
    - section3/08_encapsulation.md
  - 4. Python (OO avancé):
    - section4/01_bases.md
  - 5. Qt et PySide6:
    - section5/01_bases.md
  - 6. Patrons de conception:
    - section6/01_bases.md
  - 7. Pygame:
    - section7/01_bases.md

theme:
  name: material
  locale: fr
  language: fr
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    logo: material/language-python
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


extra_css:
  - style.css

markdown_extensions:
    smarty: { }
    toc:
      permalink: true
    sane_lists: { }
    admonition: { }
    attr_list: {}
    pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    pymdownx.inlinehilite: { }
    pymdownx.snippets: {}
    pymdownx.superfences: { }
    pymdownx.fancylists: { }
    pymdownx.saneheaders: { }
    pymdownx.mark: { }
    pymdownx.tabbed: { }
    pymdownx.tasklist: { }
    pymdownx.tilde: { }
    pymdownx.details: { }
    pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        theme:
          enabled: false
    - search: {}